# This is a boilerplate parameters config generated for pipeline 'data_science'
# using Kedro 0.19.13.
#
# Documentation for this file format can be found in "Parameters"
# Link: https://docs.kedro.org/en/0.19.13/configuration/parameters.html


# Models hiperparameters
split_data_params:
  test_size: 0.2
  random_state: 42

model_params:
  logistic_regression:
    model_type: "LogisticRegression"
    penalty: "l2"
    C: 1.0
    random_state: 42
  random_forest_classifier:
    model_type: "RandomForestClassifier"
    n_estimators: 100
    criterion: "gini"
    max_depth: 5
    random_state: 42
  xgboost_classifier:  
    model_type: "XGBClassifier"
    n_estimators: 100
    max_depth: 5
    learning_rate: 0.1
    random_state: 42
  support_vector_classifier:
    model_type: "SVC"
    kernel: "rbf"
    C: 1.0
    gamma: "scale"
    random_state: 42
  balanced_random_forest_classifier:
    model_type: "BalancedRandomForestClassifier"
    n_estimators: 100
    criterion: "gini"
    max_depth: 5
    random_state: 42
